apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env
  labels:
    app: env-demo
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ['sh', '-c', 'echo "APP_NAME=$APP_NAME" && echo "APP_VERSION=$APP_VERSION" && sleep 3600']
    
    # Переменные окружения
    env:
    - name: APP_NAME
      value: "my-awesome-app"
    - name: APP_VERSION
      value: "1.0.0"
    - name: ENVIRONMENT
      value: "development"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

