apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-labels
  labels:
    app: web
    tier: frontend
    environment: dev
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
      name: http

