apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
    app: nginx-np
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Доступ: minikube ip + :30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nodeport-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-np
  template:
    metadata:
      labels:
        app: nginx-np
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80

