apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATABASE_URL: "postgres://db.example.com:5432/mydb"
  APP_NAME: "MyAwesomeApp"
  APP_MODE: "production"
  LOG_LEVEL: "info"

---
apiVersion: v1
kind: Pod
metadata:
  name: app-with-config
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ['sh', '-c', 'echo "DATABASE_URL=$DATABASE_URL" && echo "APP_NAME=$APP_NAME" && sleep 3600']
    envFrom:
    - configMapRef:
        name: app-config

